language: node_js
node_js:
  - "6"
os:
  - osx
sudo: false
before_install:
  - npm install -g typescript mocha istanbul remap-istanbul postinstall-build
  - npm install chai typemoq --save-dev
  - npm install @types/{mocha,chai} --save-dev
script:
  - npm run build
  - npm run test
